### ISSUE TITLE
[13.0] Error on creation -  Apply computed create permissions.

### ISSUE THREAD

**Issue by rbellanova** [OCA/dms#114]
Hello dears,
After the last updates, I got an error on directories creation as you can see on the GIF.
I used also a void Database.
I noticed that the directories are created, because you can see the ID that always change on the errors.

![Peek 09-07-2021 12-08](https://user-images.githubusercontent.com/42999048/125062609-dfe21880-e0ae-11eb-8cfb-cb98203f0626.gif)

**Comment by victoralmau** [comment]
Hello, I do not know the version, but I think the error happens because there are no groups defined in the directory that is trying to create (it is necessary that at least one exists for the user with creation permissions).

**Comment by rbellanova** [comment]
Sorry... It happens even at the first configuration with the onboarding...it's 13.0 version with dms updated to 13.0.7.0.1....and I'm using super admin... void database

**Comment by victoralmau** [comment]
It's not error now, it's correct way to work because although we use admin user if directory haven't any group, what permission sould be apply? Now, is required to add group to directory (specially if directory is root) because apply rules (create,write and unlink) according to complete groups.
Example about error in directory creation now:
![dms-error](https://user-images.githubusercontent.com/4117568/125065524-356bf480-e0b2-11eb-80c6-ff86b4be684c.gif)

Example about correct way to directory creation now:
![dms-ok](https://user-images.githubusercontent.com/4117568/125065548-3a30a880-e0b2-11eb-8584-ac64a1c117d1.gif)

**Comment by rbellanova** [comment]
Oh great! Thank you for the explainations
