### ISSUE TITLE
[12.0] Permission problem

### ISSUE THREAD

**Issue by miscs** [OCA/dms#118]
Hi all,

since permission changes (https://github.com/OCA/dms/commit/c147000d605ba03c2c6188734441b535906cc063) I have problems to get DMS working with dms_field and res.partner model in odoo 12.0:

What works:
I can create a new storage (filestorage) without linked model. When I create a root-directory for that storage I need to assign an access group during create. If I dont do this, I get an error. With access group assigned, the directory will be created and I can upload files.

Permission problem:
But when I use dms_field and link res.partner model to the storage I cannot assign an access group -> in partner view I try to attach the storage (view from demo). I can select my storage in dropdown, but when I select it I get the following error:

"The requested operation cannot be completed due to security restrictions. Please contact your system administrator."

I think this is because there is no access group assigned to the directory to be created, but in the view there is no possibility to select one. Any chance to set a standard access group for the whole storage or other ideas how to solve this?

Thanks!
Steve

**Comment by victoralmau** [comment]
Hello,

Previously you could create folders without assigning groups (and permissions) and there was no problem but that was not really correct because you did not have any permissions.

Some solutions could be:

- Add the groups field to the `dms_field` addon so that they can be specified from there and solve the problem.
- When the folder is created, relate it to a storage configured as `type=attachment` and set "_Inherit permissions from related record_"

All the best.

**Comment by miscs** [comment]
Thank you for the quick answer. I just tried your second suggestion and it works for me.

Thanks!
Steve
