### ISSUE TITLE
[14.0]Can not upload file by drag & drop

### ISSUE THREAD

**Issue by emitcscloud** [OCA/dms#129]
Even if I select a directoy, When upload files by drag & drog，we will catch an error:
 You must select a directory first 
The same opteration was work correct in version 13

**Comment by pedrobaeza** [comment]
Please specify whole detailed steps to reproduce the problem.

**Comment by victoralmau** [comment]
Hello,

Although no specified steps to reproduce error, I think the drag & drop bug in v13 happens since this change https://github.com/OCA/web/pull/2036 and resolved with this: https://github.com/OCA/web/pull/2036

In V14 this correction is pending with: https://github.com/OCA/dms/pull/145

This is correct, right?

**Comment by victoralmau** [comment]
Hi, it's solved on 14.0 (https://github.com/OCA/dms/pull/145)
