### ISSUE TITLE
authorization in display only

### ISSUE THREAD

**Issue by ccandito** [OCA/dms#254]
Hi,
I would authorize some users to display files in some directories only.
I've tried by using authorization groups by assigning them directory and users but it does not work out.
Can someone suggest me how to solve it?
Regards
Claudio Candito

**Comment by marylla** [comment]
@ccandito Can you give more details about what you tried already and in which version and what exactly did not work out?

You need to create an access group with at least the read permission.
Then you add the users that are part of this group.
Then you assign this access groups to the directory.
Users that are not in this group cannot see the files of this directory.
I guess, if a directory has no access group at all, then all dms users can see the files of this directory.

If you have several access groups for this directory you might check all of them. They might overlap somehow?

**Comment by ccandito** [comment]
Dear Marylla,
thanks for answering me.
Version 15.
I've created only one access group and assigned it to an user with "user" permission.
This access group has read permission only, but the user can still change/create records belonging the directory that the access group has been assigned to.
Regards
claudio Candito

**Comment by marylla** [comment]
@ccandito Okay, but this user is not the admin? Because I had a similiar problem once when "testing" with the admin user

I tested in runboat and it works for me.

- I logged in as admin user (login and password are "admin")
- I created 2 access groups:
  - admin -> for user "admin" -> is allowed to do everything
  - read only -> for user "demo" -> is allowed to read but nothing else

![image](https://github.com/OCA/dms/assets/9402177/15a0ff29-881b-40b0-89ad-964479cdf946)

- I created a test folder with both access groups

![image](https://github.com/OCA/dms/assets/9402177/1da4503a-614d-4cf0-b58a-7fc2a396dd34)

- I created a new file

![image](https://github.com/OCA/dms/assets/9402177/af100f18-d812-4361-a2ca-aa8fe24721c8)

- I logged in as demo user (login and password are "demo")
- I can see the test folder, I can see the file

![image](https://github.com/OCA/dms/assets/9402177/0c2ba6a2-0f5b-430f-bf1b-2178b631fc4e)

- But I cannot change the file or delete it.

![image](https://github.com/OCA/dms/assets/9402177/27c5e242-204a-4c17-b0be-d15ac8c2c7b7)

You can test in runboat, too.

http://oca-dms-15-0-9100fc178d2d.runboat.odoo-community.org/web#id=17&cids=1&menu_id=102&action=156&model=dms.directory&view_type=form

**Comment by ccandito** [comment]
thanks a lot.
unfortunately it does not work out in enterprise edition where some functional icons have been added (see screenshot below).
are you going to move it on version 16?
Regards
Claudio

![image](https://github.com/OCA/dms/assets/8027589/f2c08b4e-1534-418c-bb37-ca1e1cd6b45e)
