### ISSUE TITLE
parent_id listed directory not the same permission meaning

### ISSUE THREAD

**Issue by viettqhome** [OCA/dms#328]
## Module
The name of the module that has a bug.
dms.directory
dms.file

## Describe the bug
parent_id listed directory not the same permission meaning
![image](https://github.com/OCA/dms/assets/75714943/d407fa94-70d1-4812-b3ab-0ff8fe5d0bd6)

## To Reproduce
**Affected versions**:
13/16

**Comment by victoralmau** [comment]
I don't really understand the problem, I guess you mean that you can select a parent directory that does not have create permissions, correct? 

Filtering the parent directories to only those that you have permissions to create I think would be a mistake, because it is possible to add new groups to that directory that you are creating in which you DO have permissions to create.
